CREATE TABLE KLIENCI(
ID_KLIENTA NUMBER(6) PRIMARY KEY CHECK(ID_KLIENTA>0),
IMIE_KLIENTA CHAR(30) NOT NULL,
NAZWISKO_KLIENTA CHAR(30) NOT NULL,
DATA_UR_KLIENTA DATE NOT NULL,
ULICA CHAR(30) NOT NULL,
NR_DOMU NUMBER(3) NOT NULL,
NR_LOKALU NUMBER(3),
MIASTO CHAR(30) NOT NULL,
KOD_POCZTOWY CHAR(6) NOT NULL,
TELEFON NUMBER (10),
EMAIL CHAR(30)
);

CREATE TABLE REZERWACJE(
ID_REZERWACJI NUMBER(6) PRIMARY KEY CHECK(ID_REZERWACJI>0),
ID_KLIENTA NUMBER(6) NOT NULL REFERENCES KLIENCI(ID_KLIENTA) CHECK(ID_KLIENTA>0),
DATA_REZERWACJI DATE NOT NULL,
POCZATEK_REZERWACJI DATE NOT NULL,
KONIEC_REZERWACJI DATE NOT NULL,
TERMIN_PLATNOSCI DATE NOT NULL,
DATA_DOKONANIA_platnosci DATE,
CHECK(POCZATEK_REZERWACJI<=KONIEC_REZERWACJI),
CHECK (DATA_REZERWACJI<=POCZATEK_REZERWACJI),
CHECK (TERMIN_PLATNOSCI >= DATA_REZERWACJI),
CHECK (DATA_DOKONANIA_PLATNOSCI BETWEEN DATA_REZERWACJI AND TERMIN_PLATNOSCI)
);

CREATE TABLE METODY_PLATNOSCI(
ID_METODY_PLATNOSCI NUMBER(1) PRIMARY KEY CHECK(ID_METODY_PLATNOSCI>0),
METODA_PLATNOSCI CHAR(20) NOT NULL,
CHECK((ID_METODY_PLATNOSCI = 1 AND METODA_PLATNOSCI = 'GOTOWKA') OR(ID_METODY_PLATNOSCI = 2 AND METODA_PLATNOSCI = 'KARTA') OR (ID_METODY_PLATNOSCI = 3 AND METODA_PLATNOSCI = 'CZEK') OR(ID_METODY_PLATNOSCI = 4 AND METODA_PLATNOSCI = 'PRZELEW')) 
);

CREATE TABLE PLATNOSCI(
ID_PLATNOSCI NUMBER(6) PRIMARY KEY CHECK(ID_PLATNOSCI>0),
ID_REZERWACJI NUMBER(6) NOT NULL REFERENCES REZERWACJE(ID_REZERWACJI) CHECK (ID_REZERWACJI>0),
ID_KLIENTA NUMBER(6) NOT NULL REFERENCES KLIENCI(ID_KLIENTA) CHECK(ID_KLIENTA>0),
ID_METODY_PLATNOSCI NUMBER(1) NOT NULL REFERENCES METODY_PLATNOSCI(ID_METODY_PLATNOSCI) CHECK(ID_METODY_PLATNOSCI BETWEEN 1 AND 4),
WYSOKOSC_OPLATY NUMBER(6,2) NOT NULL CHECK(WYSOKOSC_OPLATY>0)
);

CREATE TABLE TYPY_POKOI(
TYP_POKOJU_ID NUMBER(1) PRIMARY KEY,
TYP_POKOJU CHAR(20) NOT NULL,
CHECK((TYP_POKOJU_ID = 1 AND TYP_POKOJU = 'JEDNOOSOBOWY') OR(TYP_POKOJU_ID = 2 AND TYP_POKOJU = 'DWUOSOBOWY') OR (TYP_POKOJU_ID = 3 AND TYP_POKOJU = 'TRZYOSOBOWY') OR(TYP_POKOJU_ID = 4 AND TYP_POKOJU = 'CZTEROOSOBOWY')) 
);

CREATE TABLE KLASY_POKOI(
KLASA_POKOJU_ID NUMBER(1) PRIMARY KEY,
KLASA_POKOJU CHAR(20) NOT NULL,
CHECK((KLASA_POKOJU_ID = 1 AND KLASA_POKOJU = 'EKONOMICZNY') OR (KLASA_POKOJU_ID = 2 AND KLASA_POKOJU = 'ZWYKLY') OR (KLASA_POKOJU_ID = 3 AND KLASA_POKOJU = 'PODWYZSZONY STANDARD') OR (KLASA_POKOJU_ID = 4 AND KLASA_POKOJU = 'WYSOKI STANDARD') OR (KLASA_POKOJU_ID = 5 AND KLASA_POKOJU = 'LUKSUSOWY'))
);

CREATE TABLE CENY_POKOI(
CENA_POKOJU_ID NUMBER(2) PRIMARY KEY,
CENA_POKOJU NUMBER(4) NOT NULL
);

CREATE TABLE POKOJE(
NR_POKOJU NUMBER(3) PRIMARY KEY CHECK (NR_POKOJU>0),
TYP_POKOJU_ID NUMBER(1) NOT NULL CHECK(TYP_POKOJU_ID BETWEEN 1 AND 4),
KLASA_POKOJU_ID NUMBER(1) NOT NULL CHECK(KLASA_POKOJU_ID BETWEEN 1 AND 5),
CENA_POKOJU_ID NUMBER(2) NOT NULL 
);

CREATE TABLE GOSCIE(
GOSC_ID NUMBER(6) PRIMARY KEY CHECK (GOSC_ID>0),
IMIE_GOSCIA CHAR(30) NOT NULL,
NAZWISKO_GOSCIA CHAR(30) NOT NULL,
DATA_UR_GOSCIA DATE NOT NULL,
ULICA CHAR(30) NOT NULL,
NR_DOMU NUMBER(3) NOT NULL,
NR_LOKALU NUMBER(3),
MIASTO CHAR(30) NOT NULL,
KOD_POCZTOWY CHAR(6) NOT NULL,
TELEFON NUMBER (10)
);

CREATE TABLE REZERWACJE_POKOJE_GOSCIE(
ID_REZERWACJI NUMBER(6) NOT NULL REFERENCES REZERWACJE(ID_REZERWACJI) CHECK(ID_REZERWACJI>0),
NR_POKOJU NUMBER(3) NOT NULL REFERENCES POKOJE(NR_POKOJU) CHECK (NR_POKOJU>0),
GOSC_ID NUMBER(6) NOT NULL REFERENCES GOSCIE(GOSC_ID) CHECK (GOSC_ID >0),
PRIMARY KEY(ID_REZERWACJI, NR_POKOJU, GOSC_ID)
);